---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: deny-by-default
  namespace: stellar-wallet-server
  labels:
    app: stellar-wallet-server
spec:
  podSelector: {}
  ingres: []
...
